"""Live user profile — auto-observed facts under a marker the user owns.

The briefing's "About you & what you expect" setting (``briefing_user_context``,
max 4096 chars) is user-edited free text injected into every synthesis prompt
as trusted context. Making it LIVE means an LLM pass periodically mines the
recent personal corpus for durable facts — but a model writing into a trusted
prompt slot is a prompt-injection and hallucination surface, so this module
enforces three invariants in code rather than by instruction:

1. **The user's prose is never touched.** Auto-observed facts live under an
   explicit marker line (``AUTO_MARKERS``); ``split_profile`` /
   ``merge_profile`` partition on that line, and the merge only ever rebuilds
   the section *below* it. The 4096-char cap is honoured by dropping
   observations from the end — never by cutting the user part.
2. **An observation must be grounded.** ``propose_observations`` keeps a
   proposal only if it shares distinctive vocabulary with the signals it was
   mined from — an observation the corpus never mentioned is a hallucination
   and is dropped in code, not by asking the model nicely.
3. **The profile grounds the world-news "→ Impact" lines.** An impact line
   that shares no distinctive token with the profile (``impact_grounded``)
   is an invented hook; the caller strips it.

Token matching is prefix-6 to tolerate French/English inflection
("investissements" / "investir" both reduce to "invest").
"""

from __future__ import annotations

import json
import re
from collections.abc import Awaitable, Callable

# Async LLM callable bound to provider/model by the orchestrator; forwards
# per-call decode options (max_tokens / temperature / json_schema / timeout).
ProfileLlm = Callable[..., Awaitable[str]]

# Hard cap of the ``briefing_user_context`` setting (enforced by the web UI on
# the user's side, by ``merge_profile`` on ours).
MAX_PROFILE_CHARS = 4096

# The line separating the user's own prose (above, never touched by code)
# from the auto-observed section (below, regenerated by the LLM pass and
# editable/deletable by the user in the web UI). English first, French second.
AUTO_MARKERS: tuple[str, ...] = (
    "— Auto-observed (you can edit or delete this) —",
    "— Observations automatiques (modifiables) —",
)


def auto_marker(lang: str) -> str:
    """The marker for ``lang`` ('fr' → the French one, anything else → English)."""
    return AUTO_MARKERS[1] if lang == "fr" else AUTO_MARKERS[0]


def split_profile(text: str) -> tuple[str, str]:
    """(user_part, auto_part) split on the FIRST line equal to any AUTO_MARKER
    (line-stripped compare). auto_part excludes the marker line. No marker →
    (text, "")."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() in AUTO_MARKERS:
            return "\n".join(lines[:i]), "\n".join(lines[i + 1 :])
    return text, ""


def merge_profile(user_part: str, observations: list[str], lang: str) -> str:
    """user_part + blank line + marker + '- obs' lines. Empty observations →
    user_part unchanged (stripped trailing whitespace). HARD CAP 4096 chars:
    drop observations from the END until it fits — never cut the user part."""
    base = user_part.rstrip()
    # One observation = one plain-text line: collapse internal newlines (they
    # would render as extra bullets in the UI textarea), drop markdown
    # emphasis, and cut at a word boundary instead of mid-word.
    kept: list[str] = []
    for o in observations:
        o = " ".join(o.replace("*", "").split()).strip()
        if len(o) > 160:
            o = o[:160].rsplit(" ", 1)[0].rstrip(" ,;:—-") + "…"
        if o:
            kept.append(o)
    marker = auto_marker(lang)
    while kept:
        bullets = "\n".join(f"- {o}" for o in kept)
        section = f"{marker}\n{bullets}"
        merged = f"{base}\n\n{section}" if base else section
        if len(merged) <= MAX_PROFILE_CHARS:
            return merged
        kept.pop()
    return base


# Grammar-locked output shape for ``propose_observations``: a bare list of
# short strings — no nesting a small model could truncate mid-object.
PROFILE_OBS_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "observations": {
            "type": "array",
            "minItems": 0,
            "maxItems": 8,
            "items": {"type": "string", "maxLength": 160},
        }
    },
    "required": ["observations"],
}

_OBS_OPTS = {
    "max_tokens": 700,
    "temperature": 0.1,
    "timeout": 300.0,
    "json_schema": PROFILE_OBS_SCHEMA,
    "stage": "profile",
}

# Generic French + English function/common words that would otherwise ground
# anything against anything. Small on purpose: the >=5-chars length gate in
# ``distinctive_tokens`` already drops most short function words ("the",
# "les", "des", …) for free.
_STOPWORDS: frozenset[str] = frozenset(
    {
        # French
        "avec",
        "pour",
        "dans",
        "chez",
        "cette",
        "leur",
        "leurs",
        "votre",
        "notre",
        "vous",
        "nous",
        "tout",
        "toute",
        "toutes",
        "plus",
        "moins",
        "aussi",
        "comme",
        "être",
        "avoir",
        "faire",
        "entre",
        "depuis",
        "encore",
        "matin",
        "journée",
        "semaine",
        "attends",
        # English
        "about",
        "this",
        "that",
        "with",
        "from",
        "what",
        "when",
        "where",
        "which",
        "your",
        "their",
        "have",
        "will",
        "would",
        "could",
        "should",
        "there",
        "these",
        "those",
        "every",
        "daily",
        "while",
        "being",
        "briefing",
        "morning",
        "expect",
    }
)

_TOKEN_RE = re.compile(r"[^\W_]+", re.UNICODE)


def distinctive_tokens(text: str) -> set[str]:
    """Lowercased tokens >=5 chars or digit-bearing (>=2 chars), minus a small
    generic French+English stopword set."""
    tokens: set[str] = set()
    for tok in _TOKEN_RE.findall(text.lower()):
        if tok in _STOPWORDS:
            continue
        if len(tok) >= 5 or (len(tok) >= 2 and any(c.isdigit() for c in tok)):
            tokens.add(tok)
    return tokens


def impact_grounded(line: str, profile_tokens: set[str]) -> bool:
    """True when ``line`` shares >=1 distinctive token with the profile,
    prefix-6 matching to tolerate inflection ('investissements'/'investir')."""
    line_prefixes = {t[:6] for t in distinctive_tokens(line)}
    profile_prefixes = {t[:6] for t in profile_tokens}
    return bool(line_prefixes & profile_prefixes)


async def propose_observations(
    llm: ProfileLlm,
    user_part: str,
    current_auto: str,
    signals: list[str],
    language: str = "French",
    opts: dict | None = None,
) -> list[str]:
    """Ask the LLM for 3-8 durable observations; ground-filter them in code."""
    signals_blob = "\n".join(signals)
    prompt = (
        "You maintain the auto-observed section of a user profile that a "
        "morning-briefing writer relies on every day.\n"
        f"Propose 3-8 durable observations about the user, written in {language}.\n\n"
        "USER'S OWN PROFILE TEXT (written by the user — never duplicate it):\n"
        f"{user_part.strip() or '(empty)'}\n\n"
        "CURRENT AUTO-OBSERVED SECTION (you are proposing its replacement; "
        "keep what still holds):\n"
        f"{current_auto.strip() or '(empty)'}\n\n"
        "SIGNALS — recent excerpts from the user's personal data, one per line:\n"
        f"{signals_blob or '(none)'}\n\n"
        "Rules:\n"
        "- Only durable, recurring facts useful to a morning-briefing writer: "
        "recurring people and their relation to the user, ongoing projects, "
        "strong interests, regular activities.\n"
        "- NO one-off events.\n"
        "- NO sensitive inferences (health conditions, politics, religion, "
        "sexuality).\n"
        "- No duplicates of what the user already wrote.\n"
        "- Each observation is ONE short line.\n\n"
        'Answer with JSON only: {"observations": ["...", ...]}'
    )
    try:
        raw = await llm(prompt, **(opts or _OBS_OPTS))
        parsed = json.loads(raw)
        proposed = parsed["observations"]
        if not isinstance(proposed, list):
            return []
    except Exception:
        return []

    # Code-side hallucination guard: an observation the signals never
    # mentioned (no shared distinctive token, prefix-6) is invented — drop it.
    signal_tokens = distinctive_tokens(signals_blob)
    kept: list[str] = []
    seen: set[str] = set()
    for obs in proposed:
        if not isinstance(obs, str):
            continue
        obs = obs.strip()
        if not obs or len(obs) > 160:
            continue
        key = " ".join(obs.lower().split())
        if key in seen:
            continue
        if not impact_grounded(obs, signal_tokens):
            continue
        seen.add(key)
        kept.append(obs)
        if len(kept) == 8:
            break
    return kept
