"""Contract: the bundle's third-party-license collection cannot silently drop a
dependency's attribution.

`make bundle` copies each wheel's license text into
``Estormi.app/Contents/Resources/THIRD-PARTY-LICENSES/``. A wheel that ships no
``LICENSE*`` file in its dist-info would otherwise be omitted — the gap that left
the deployed app missing odfpy (LGPL-2.1, imported in production) and ~13 other
packages while NOTICE promised "every bundled Python package". These tests pin
the three guards that close it, without needing a built bundle:

1. the Makefile collection step has the ``METADATA`` fallback (so no package is
   omitted) and collects the Rust attribution;
2. the copyleft text a wheel omits is vendored under ``make/extra-licenses/``
   (odfpy → verbatim LGPL-2.1);
3. NOTICE describes odfpy as LGPL (not GPL) and the Rust attribution baseline is
   present and non-trivial.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
BUNDLE_MK = REPO_ROOT / "make" / "bundle.mk"
NOTICE = REPO_ROOT / "NOTICE"
EXTRA_LICENSES = REPO_ROOT / "make" / "extra-licenses"
RUST_ATTRIB = REPO_ROOT / "apps" / "estormi-macos" / "THIRD-PARTY-RUST.md"

pytestmark = pytest.mark.contract


def test_collection_has_metadata_fallback() -> None:
    """A wheel with no LICENSE file must fall back to its METADATA declaration."""
    mk = BUNDLE_MK.read_text(encoding="utf-8")
    assert "METADATA-LICENSE.txt" in mk, (
        "make/bundle.mk lost the METADATA fallback — wheels without a LICENSE "
        "file (odfpy, mistral_common, sentencepiece, …) would be silently "
        "omitted from THIRD-PARTY-LICENSES/."
    )
    # The fallback only fires when no real license file was found.
    assert re.search(r"found=0.*METADATA", mk, re.DOTALL), (
        "the METADATA fallback should only apply when no LICENSE/COPYING/NOTICE/"
        "AUTHORS file was collected (found=0)."
    )


def test_collection_overlays_extra_licenses_and_rust() -> None:
    """The collection step overlays make/extra-licenses/ and ships the Rust text."""
    mk = BUNDLE_MK.read_text(encoding="utf-8")
    assert "make/extra-licenses" in mk, (
        "make/bundle.mk no longer overlays the vendored make/extra-licenses/ "
        "texts — odfpy's LGPL-2.1 text would not reach the bundle."
    )
    assert "THIRD-PARTY-RUST.md" in mk, (
        "make/bundle.mk no longer collects the Rust crate attribution "
        "(THIRD-PARTY-RUST.md) into the bundle."
    )


def test_odfpy_lgpl_text_is_vendored() -> None:
    """odfpy ships no wheel LICENSE, so its verbatim LGPL-2.1 text must be vendored."""
    odfpy = EXTRA_LICENSES / "odfpy"
    assert odfpy.is_dir(), (
        "make/extra-licenses/odfpy/ is missing — the LGPL-2.1 obligation for the "
        "odf library (imported in estormi_ingestion/documents/ingest_documents.py) "
        "would go unmet in the shipped bundle."
    )
    texts = [p for p in odfpy.iterdir() if p.is_file() and p.name != "README.md"]
    assert texts, "make/extra-licenses/odfpy/ has no license text file."
    blob = "\n".join(p.read_text(encoding="utf-8", errors="ignore") for p in texts)
    assert "GNU LESSER GENERAL PUBLIC LICENSE" in blob
    assert "Version 2.1" in blob, "the vendored odfpy text must be LGPL v2.1."


def test_notice_describes_odfpy_as_lgpl_not_gpl() -> None:
    """NOTICE must not mischaracterise the imported odf library as GPL."""
    notice = NOTICE.read_text(encoding="utf-8")
    # Find the odfpy bullet and assert it leads with LGPL.
    m = re.search(r"\*\*odfpy\*\*.*?(?=\n- \*\*|\nRust crates|\Z)", notice, re.DOTALL)
    assert m, "could not find the odfpy entry in NOTICE."
    entry = m.group(0)
    assert "LGPL-2.1" in entry, "NOTICE should describe odfpy's odf library as LGPL-2.1."


def test_rust_attribution_baseline_present() -> None:
    """The committed Rust attribution must exist and be non-trivial."""
    assert RUST_ATTRIB.is_file(), (
        "apps/estormi-macos/THIRD-PARTY-RUST.md is missing — run "
        "`make rust-licenses` to generate it. `make bundle` ships this committed "
        "baseline so MIT/Apache crate notices accompany the binary."
    )
    text = RUST_ATTRIB.read_text(encoding="utf-8")
    # Generated by cargo-about: dozens of license sections, must include the
    # workhorse permissive texts the shell links.
    assert text.count("\n## ") >= 5, "Rust attribution looks empty/truncated."
    assert "MIT License" in text or "MIT/X11" in text or "Permission is hereby granted" in text
    assert "Apache License" in text
